export interface MenuItem {
  id: string
  name: string
  description: string
  price: number
  category: string
  image?: string
  variants?: { name: string; price: number }[]
}

export const MENU_CATEGORIES = [
  "Breakfast Bonanza",
  "Taste of Tamil Nadu",
  "Soup Spot",
  "Salad Symphony",
  "Bistro Bites",
  "Flavorful Starter",
  "Choice of Bread",
  "Rice Bowl",
  "Arabian Master",
  "Kiddie Meal",
  "Extras & More",
] as const

export const MENU_ITEMS: MenuItem[] = [
  // Breakfast Bonanza
  {
    id: "super-signature-breakfast",
    name: "Super Signature Breakfast",
    description:
      "Choice of stir-fried chicken or beef strips, served with a sunny-side up egg, home-cut fries, baked beans, toasted bread with a choice of tea, coffee or juice.",
    price: 28000,
    category: "Breakfast Bonanza",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/216829-7iclcfdARF2GMC1ElU66XDDdJ8TOIS.jpg",
  },
  {
    id: "bistro-house-breakfast",
    name: "Bistro House Breakfast",
    description:
      "Fried egg, pair of sausages, home-cut fries, baked beans and toasted bread with a choice of tea, coffee or juice.",
    price: 25000,
    category: "Breakfast Bonanza",
  },
  {
    id: "hungry-man-combo",
    name: "Hungry-Man Combo",
    description: "Choice of chicken or beef rolex, served with home-cut fries and your choice of tea, coffee or juice",
    price: 20000,
    category: "Breakfast Bonanza",
  },
  {
    id: "breakfast-chicken-wrap",
    name: "Breakfast Chicken Wrap",
    description:
      "Grilled chicken strip with vegetables and melted cheese, wrapped and served with home-cut fries and your choice of tea, coffee or juice",
    price: 20000,
    category: "Breakfast Bonanza",
  },
  {
    id: "breakfast-egg-sandwich",
    name: "Breakfast Egg Sandwich",
    description:
      "A flavorful Spanish omelette on toasted bread, served with home-cut fries and a choice of tea, coffee or juice",
    price: 18000,
    category: "Breakfast Bonanza",
  },
  {
    id: "loaded-rolex",
    name: "Loaded Rolex",
    description:
      "A juicy Ugandan twist with your choice of chicken or beef - chapati rolled with omelette, onions, tomatoes, and cabbage",
    price: 10000,
    category: "Breakfast Bonanza",
  },
  {
    id: "egg-rolex",
    name: "Egg Rolex",
    description: "A classic ugandan swirl - chapati rolled with omelette, onions, tomatoes, and cabbage",
    price: 7000,
    category: "Breakfast Bonanza",
  },
  {
    id: "fried-egg",
    name: "Fried Egg",
    description: "Cooked to Perfection.",
    price: 5000,
    category: "Breakfast Bonanza",
  },
  {
    id: "sunny-side-up",
    name: "Sunny Side Up",
    description: "A delicate, runny-yolked egg.",
    price: 5000,
    category: "Breakfast Bonanza",
  },
  {
    id: "omelette",
    name: "Omelette",
    description: "Fluffy omelette with choice of fillings.",
    price: 7000,
    category: "Breakfast Bonanza",
  },
  {
    id: "egg-burji",
    name: "Egg Burji",
    description: "Spicy scrambled with onions and tomatoes.",
    price: 8000,
    category: "Breakfast Bonanza",
  },
  {
    id: "chilli-egg",
    name: "Chilli Egg",
    description: "Omelette with spicy onions and tomatoes",
    price: 10000,
    category: "Breakfast Bonanza",
  },

  // Taste of Tamil Nadu
  {
    id: "uthappam",
    name: "Uthappam",
    description: "Topped with onions and tomato, served with chutney and sambar",
    price: 10000,
    category: "Taste of Tamil Nadu",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/216830-hfZjLQVIoTK5qCc143ryuxo1KuyJGb.jpg",
  },
  {
    id: "plain-dosa",
    name: "Plain Dosa",
    description: "Served with chutney and sambar",
    price: 10000,
    category: "Taste of Tamil Nadu",
  },
  {
    id: "ghee-roast",
    name: "Ghee Roast",
    description: "Served with chutney and sambar",
    price: 12000,
    category: "Taste of Tamil Nadu",
  },
  {
    id: "cheese-dosa",
    name: "Cheese Dosa",
    description: "Served with chutney and sambar",
    price: 15000,
    category: "Taste of Tamil Nadu",
  },
  {
    id: "masala-dosa",
    name: "Masala Dosa",
    description: "Stuffed with spiced potatoes and onions, served with chutney and sambar",
    price: 15000,
    category: "Taste of Tamil Nadu",
  },
  {
    id: "poori-bhaji",
    name: "Poori Bhaji",
    description: "Served with potatoes and peas masala",
    price: 15000,
    category: "Taste of Tamil Nadu",
  },

  // Soup Spot
  {
    id: "cream-of-tomato",
    name: "Cream of Tomato",
    description: "Fresh tomatoes blended with aromatic herbs and spices",
    price: 12000,
    category: "Soup Spot",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/216830-hfZjLQVIoTK5qCc143ryuxo1KuyJGb.jpg",
  },
  {
    id: "cream-of-mushroom",
    name: "Cream of Mushroom",
    description: "Rich and creamy mushroom soup with flavors and a hint of spice",
    price: 12000,
    category: "Soup Spot",
  },
  {
    id: "clear-vegetable",
    name: "Clear Vegetable",
    description: "Flavorful broth with a colorful medley of vegetables and sweet corn.",
    price: 12000,
    category: "Soup Spot",
  },
  {
    id: "chicken-and-corn",
    name: "Chicken and Corn",
    description: "A comforting blend of chicken and corn with a hint of herbs",
    price: 14000,
    category: "Soup Spot",
  },
  {
    id: "chicken-manchow",
    name: "Chicken Manchow",
    description: "Spicy and savory chicken noodle soup",
    price: 15000,
    category: "Soup Spot",
  },

  // Salad Symphony
  {
    id: "mixed-garden-salad",
    name: "Mixed Garden Salad",
    description: "Garden greens, cherry tomatoes, and cucumber with house dressing.",
    price: 22000,
    category: "Salad Symphony",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/216831-UFEB3R8mDf2BEI0pHaMCWt42HcSgUO.jpg",
  },
  {
    id: "chicken-caesar",
    name: "Chicken Caesar",
    description: "Grilled chicken breast, lettuce, and parmesan cheese with Caesar dressing",
    price: 25000,
    category: "Salad Symphony",
  },
  {
    id: "avocado-mango",
    name: "Avocado & Mango",
    description: "A refreshing blend of avocado and mango mixed with house dressing",
    price: 20000,
    category: "Salad Symphony",
  },

  // Bistro Bites
  {
    id: "vegetable-samosa",
    name: "Vegetable Samosa",
    description: "2pcs",
    price: 5000,
    category: "Bistro Bites",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/216831-UFEB3R8mDf2BEI0pHaMCWt42HcSgUO.jpg",
  },
  {
    id: "beef-samosa",
    name: "Beef Samosa",
    description: "2pcs",
    price: 6000,
    category: "Bistro Bites",
  },
  {
    id: "chicken-spring-roll",
    name: "Chicken Spring Roll",
    description: "2pcs",
    price: 7000,
    category: "Bistro Bites",
  },
  {
    id: "chicken-pie",
    name: "Chicken Pie",
    description: "",
    price: 7000,
    category: "Bistro Bites",
  },
  {
    id: "egg-pie",
    name: "Egg Pie",
    description: "",
    price: 5000,
    category: "Bistro Bites",
  },
  {
    id: "bread-pocket-chicken-shawarma",
    name: "Bread Pocket Chicken Shawarma",
    description: "",
    price: 10000,
    category: "Bistro Bites",
  },

  // Flavorful Starter
  {
    id: "chicken-tikka",
    name: "Chicken Tikka",
    description: "Char grilled to perfection with a blend of yogurt and spices",
    price: 22000,
    category: "Flavorful Starter",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/216831-UFEB3R8mDf2BEI0pHaMCWt42HcSgUO.jpg",
  },
  {
    id: "chicken-lollipop",
    name: "Chicken Lollipop",
    description: "Crispy Chicken lollipop tossed in a sweet and spicy sauce.",
    price: 22000,
    category: "Flavorful Starter",
  },
  {
    id: "dry-spicy-65-mushroom",
    name: "Dry & Spicy 65 - Mushroom",
    description: "Authentic deep fried with spices",
    price: 15000,
    category: "Flavorful Starter",
  },
  {
    id: "dry-spicy-65-chicken",
    name: "Dry & Spicy 65 - Chicken",
    description: "Authentic deep fried with spices",
    price: 20000,
    category: "Flavorful Starter",
  },
  {
    id: "dry-spicy-65-paneer",
    name: "Dry & Spicy 65 - Paneer",
    description: "Authentic deep fried with spices",
    price: 18000,
    category: "Flavorful Starter",
  },
  {
    id: "chukka-mutton",
    name: "Chukka - Mutton",
    description: "Semi-dry traditional flavor",
    price: 22000,
    category: "Flavorful Starter",
  },
  {
    id: "chukka-chicken",
    name: "Chukka - Chicken",
    description: "Semi-dry traditional flavor",
    price: 20000,
    category: "Flavorful Starter",
  },
  {
    id: "chukka-beef",
    name: "Chukka - Beef",
    description: "Semi-dry traditional flavor",
    price: 22000,
    category: "Flavorful Starter",
  },
  {
    id: "chilli-mushroom",
    name: "Chilli - Mushroom",
    description: "A colourful melody of semi gravy with Peppers",
    price: 18000,
    category: "Flavorful Starter",
  },
  {
    id: "chilli-chicken",
    name: "Chilli - Chicken",
    description: "A colourful melody of semi gravy with Peppers",
    price: 22000,
    category: "Flavorful Starter",
  },
  {
    id: "chilli-paneer",
    name: "Chilli - Paneer",
    description: "A colourful melody of semi gravy with Peppers",
    price: 20000,
    category: "Flavorful Starter",
  },

  // Choice of Bread
  {
    id: "african-chappati",
    name: "African Chappati",
    description: "",
    price: 2500,
    category: "Choice of Bread",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/216832-xwTARueMTPVxwG496bVf95i5WB8Mqh.jpg",
  },
  {
    id: "phulka-chappati",
    name: "Phulka Chappati",
    description: "",
    price: 2000,
    category: "Choice of Bread",
  },
  {
    id: "south-indian-parotta",
    name: "South Indian Parotta",
    description: "",
    price: 2500,
    category: "Choice of Bread",
  },
  {
    id: "plain-naan",
    name: "Plain Naan",
    description: "",
    price: 4000,
    category: "Choice of Bread",
  },
  {
    id: "butter-naan",
    name: "Butter Naan",
    description: "",
    price: 5000,
    category: "Choice of Bread",
  },
  {
    id: "chilli-naan",
    name: "Chilli Naan",
    description: "",
    price: 5000,
    category: "Choice of Bread",
  },
  {
    id: "garlic-naan",
    name: "Garlic Naan",
    description: "",
    price: 5000,
    category: "Choice of Bread",
  },
  {
    id: "cheese-naan",
    name: "Cheese Naan",
    description: "",
    price: 8000,
    category: "Choice of Bread",
  },

  // Rice Bowl
  {
    id: "plain-rice-steamed",
    name: "Plain Rice - Steamed",
    description: "",
    price: 8000,
    category: "Rice Bowl",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/216832-xwTARueMTPVxwG496bVf95i5WB8Mqh.jpg",
  },
  {
    id: "plain-rice-biryani",
    name: "Plain Rice - Biryani",
    description: "",
    price: 12000,
    category: "Rice Bowl",
  },
  {
    id: "plain-rice-mandi",
    name: "Plain Rice - Mandi",
    description: "",
    price: 12000,
    category: "Rice Bowl",
  },
  {
    id: "fried-rice-vegetable",
    name: "Fried Rice - Vegetable",
    description: "A colorful and savory mix of rice with mixed vegetables",
    price: 15000,
    category: "Rice Bowl",
  },
  {
    id: "fried-rice-egg",
    name: "Fried Rice - Egg",
    description: "A colorful and savory mix of rice with egg",
    price: 18000,
    category: "Rice Bowl",
  },
  {
    id: "fried-rice-chicken",
    name: "Fried Rice - Chicken",
    description: "A colorful and savory mix of rice with chicken",
    price: 20000,
    category: "Rice Bowl",
  },
  {
    id: "aromatic-biryani-vegetable",
    name: "Aromatic Biryani - Vegetable",
    description:
      "Basmati rice cooked with rich spices and infused with aromatic flavors, served with chicken 65 and boiled egg",
    price: 20000,
    category: "Rice Bowl",
  },
  {
    id: "aromatic-biryani-mutton",
    name: "Aromatic Biryani - Mutton",
    description:
      "Basmati rice cooked with rich spices and infused with aromatic flavors, served with chicken 65 and boiled egg",
    price: 25000,
    category: "Rice Bowl",
  },
  {
    id: "aromatic-biryani-chicken",
    name: "Aromatic Biryani - Chicken",
    description:
      "Basmati rice cooked with rich spices and infused with aromatic flavors, served with chicken 65 and boiled egg",
    price: 25000,
    category: "Rice Bowl",
  },

  // Arabian Master
  {
    id: "half-chicken-mandi",
    name: "Half Chicken - Mandi",
    description: "Tender and Juicy roasted half chicken.",
    price: 40000,
    category: "Arabian Master",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/216832-xwTARueMTPVxwG496bVf95i5WB8Mqh.jpg",
  },
  {
    id: "half-chicken-plain",
    name: "Half Chicken - Plain",
    description: "Tender and Juicy roasted half chicken.",
    price: 30000,
    category: "Arabian Master",
  },
  {
    id: "full-chicken-mandi",
    name: "Full Chicken - Mandi",
    description: "Tender and juicy roasted whole chicken",
    price: 75000,
    category: "Arabian Master",
  },
  {
    id: "full-chicken-plain",
    name: "Full Chicken - Plain",
    description: "Tender and juicy roasted whole chicken",
    price: 55000,
    category: "Arabian Master",
  },
  {
    id: "whole-goat-leg-mandi",
    name: "Whole Goat Leg - Mandi",
    description: "Tender and flavorful 1.5kg roasted whole goat leg",
    price: 85000,
    category: "Arabian Master",
  },
  {
    id: "whole-goat-leg-plain",
    name: "Whole Goat Leg - Plain",
    description: "Tender and flavorful 1.5kg roasted whole goat leg",
    price: 65000,
    category: "Arabian Master",
  },

  // Kiddie Meal
  {
    id: "fish-finger",
    name: "Fish Finger",
    description: "Crispy fish finger served with golden fries and tartar sauce",
    price: 19000,
    category: "Kiddie Meal",
    image:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/216833%20%282%29-Uy8hcGdxY37jsRQ2MENx554dj0cY8B.jpg",
  },
  {
    id: "chicken-tenders",
    name: "Chicken Tenders",
    description: "Crispy chicken tenders served with golden fries and thousand island sauce",
    price: 19000,
    category: "Kiddie Meal",
  },
  {
    id: "mini-burger",
    name: "Mini Burger",
    description: "Choice of chicken or beef patty with melted cheese in a toasted bun and served with fries",
    price: 17000,
    category: "Kiddie Meal",
  },
  {
    id: "kiddie-pizza",
    name: "Kiddie Pizza",
    description: "Choice of Margarita, Vegetable, Chicken, or Beef",
    price: 17000,
    category: "Kiddie Meal",
  },
  {
    id: "kiddie-pasta",
    name: "Kiddie Pasta",
    description: "Choice of Arrabiata, Alfredo, or Bolognese with penne or spaghetti pasta",
    price: 18000,
    category: "Kiddie Meal",
  },
  {
    id: "kiddie-biryani",
    name: "Kiddie Biryani",
    description: "Aromatic basmati rice cooked with rich spices and tender chicken, served with a boiled egg and raita",
    price: 12000,
    category: "Kiddie Meal",
  },

  // Extras & More
  {
    id: "potato-wedges",
    name: "Potato Wedges",
    description: "",
    price: 9000,
    category: "Extras & More",
    image:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/216833%20%282%29-Uy8hcGdxY37jsRQ2MENx554dj0cY8B.jpg",
  },
  {
    id: "mashed-potato",
    name: "Mashed Potato",
    description: "",
    price: 8000,
    category: "Extras & More",
  },
  {
    id: "fried-plantain",
    name: "Fried Plantain",
    description: "",
    price: 9000,
    category: "Extras & More",
  },
  {
    id: "steamed-vegetable",
    name: "Steamed Vegetable",
    description: "",
    price: 8000,
    category: "Extras & More",
  },
  {
    id: "side-salad",
    name: "Side Salad",
    description: "",
    price: 5000,
    category: "Extras & More",
  },
  {
    id: "coleslaw",
    name: "Coleslaw",
    description: "",
    price: 4000,
    category: "Extras & More",
  },
  {
    id: "kachumbari",
    name: "Kachumbari",
    description: "",
    price: 3000,
    category: "Extras & More",
  },
  {
    id: "avocado-slice",
    name: "Avocado Slice",
    description: "",
    price: 2000,
    category: "Extras & More",
  },
  {
    id: "extra-cheese",
    name: "Extra Cheese",
    description: "",
    price: 4000,
    category: "Extras & More",
  },
  {
    id: "mayonnaise",
    name: "Mayonnaise",
    description: "",
    price: 2000,
    category: "Extras & More",
  },
  {
    id: "thousand-islands",
    name: "Thousand Islands",
    description: "",
    price: 2000,
    category: "Extras & More",
  },
  {
    id: "mushroom-sauce",
    name: "Mushroom Sauce",
    description: "",
    price: 2000,
    category: "Extras & More",
  },
  {
    id: "pepper-sauce",
    name: "Pepper Sauce",
    description: "",
    price: 2000,
    category: "Extras & More",
  },
  {
    id: "bbq-sauce",
    name: "BBQ Sauce",
    description: "",
    price: 2000,
    category: "Extras & More",
  },
  {
    id: "gravy",
    name: "Gravy",
    description: "",
    price: 2000,
    category: "Extras & More",
  },
  {
    id: "add-masala",
    name: "Add Masala",
    description: "",
    price: 3000,
    category: "Extras & More",
  },
]
